### PR TITLE
Update perl_mongers.xml

### PR DESCRIPTION
**Pull request by edwart**
Fixed email address for Tony Edwardson of Milton Keynes Perl Momgers

### CODE REVIEW

**Comment by edwart** [comment]
Ta

**Comment by davorg** [comment]
Not entirely sure what happens now, to be honest.

But at some point, that change will be pushed through to the live site.

Dave...

Quoting Tony Edwardson <notifications@github.com>:

> Ta
>

**Comment by jhannah** [comment]
@davorg ya, you can WebDAV mount the live site and run `bin/xml`. Or tell me to do that. :)

**Comment by edwart** [comment]
@jhannah stil showing the old email  do you mind doing the honours  please ?

**Comment by jhannah** [comment]
@edwart done

**Comment by edwart** [comment]
Thanks that is now sorted

**Pull request merged**
