### PR TITLE
Oslo update

### PR DESCRIPTION
**Pull request by jhannah**
per https://github.com/perlorg/www.pm.org/issues/193#issuecomment-2289370246

@sjn is this correct?

### CODE REVIEW

**Comment by sjn** [comment]
> per https://github.com/perlorg/www.pm.org/issues/193#issuecomment-2289370246
> 
> @sjn is this correct?

sjn@oslo.pm is better 😬

**Comment by jhannah** [comment]
Fixed?

**Comment by sjn** [comment]
> Fixed?

Thanks! Though please keep Marcus as a tzar too, if it's not too much.

**Comment by jhannah** [comment]
Fixed?

**Review by marcusramberg — APPROVED** [review]

**Comment by jhannah** [comment]
@sjn is this the patch you want now? No?

**Comment by jhannah** [comment]
Two tsars now: https://www.pm.org/groups/233.html
The map will be fixed via #195

**Pull request merged**
