### PR TITLE
Please add new group from Okinawa, Japan.

### PR DESCRIPTION
**Pull request by perlackline**
(1) Where are you going to host your site's website?

http://okinawa.pm.org ( http://okinawapm.github.io ) 

We will hosting our pm.site to GitHub Pages.

(2) Do you want us to host a Mailman mailing list for you?

No thank you.

### CODE REVIEW

**Comment by yasu47b** [comment]
hello, I'm a member of okinawapm.

this pull request untached about one week.
does this pull request needs anything to add?
if so please mention it.

i just wonder why our request doesn't be merged.
because resent pull requests were merged in a couple days after request.

**Comment by jhannah** [comment]
hey, sorry for the delay -- I usually only get around to these every couple of weeks. Checking now.

**Comment by jhannah** [comment]
DNS request submitted. Should take effect in a day or so. Thanks.

**Comment by masakyst** [comment]
hello, I'm a member of okinawapm.
Thank you so much for accepting!!!

**Comment by jhannah** [comment]
You're welcome! Your DNS is working, so please create a website when you have some time. Thanks :)

**Comment by yasu47b** [comment]
@jhannah thank you for your  quick action. I really appreciated.

**Pull request merged**
