### PR TITLE
Adding Blair County Perl Mongers group

### PR DESCRIPTION
**Pull request by bmilliron**
Section 1

1, Please redirect to: http://bcpapm.org
2. IP: 207.38.93.77
3. CNAME: blaircountypa.pm.org

Section 2

1. We do not need a mailing list.

Thanks,
Ben Milliron

### CODE REVIEW

**Comment by jhannah** [comment]
Usually we'd encourage you to re-launch an existing city name: `group id="690" Altoona.pm Ben Milliron`

But looks like you've already registered a domain name based on your County, so I guess that's cool. :) Welcome back, by the way.

**Comment by jhannah** [comment]
@rspier please Apache redirect blaircountypa.pm.org -> bcpapm.org

**Comment by rspier** [comment]
Config setup, but something's not right.  @abh  What did I forget?

**Comment by abh** [comment]
Seems to work for me…?

$ curl -Lv blaircountypa.pm.org 2>&1 | grep Location:
< Location: https://blaircountypa.pm.org/
< Location: http://bcpapm.org/

**Comment by rspier** [comment]
* Server certificate:
* 	 subject: /O=Acme Co/CN=Kubernetes Ingress Controller Fake Certificate
* 	 start date: 2017-10-18 04:59:44 GMT
* 	 expire date: 2018-10-18 04:59:44 GMT
* 	 common name: Kubernetes Ingress Controller Fake Certificate (does not match 'blaircountypa.pm.org')
* 	 issuer: /O=Acme Co/CN=Kubernetes Ingress Controller Fake Certificate

**Comment by abh** [comment]
Doh. All the ingress pods should have restarted now (about 20 minutes ago). Do you still see it?

**Comment by rspier** [comment]
It's fine. The issue was an old non-SNI compliant curl.  Sorry for the goose chase.

**Pull request merged**
