### PR TITLE
Re-activating the Omaha group

### PR DESCRIPTION
**Pull request by NW7US**
Per Jay's suggestion, I am forking and reactivating the Omaha group.  Thanks.

### CODE REVIEW

**Comment by jhannah** [comment]
@NW7US hey so currently omaha.pm.org is one of my Linodes, which I'll probably shut down soon...

    ✗ host omaha.pm.org
    omaha.pm.org is an alias for omaha.pm.jays.net.

How do you want to host the website?

**Comment by NW7US** [comment]
I have a hosted start here:

http://perl4ever.org/

I need to have the omaha.pm.org point to this URL for now:
http://perl4ever.org/

Is there a place where I do that?  Or is that something you can and would
take care of?

Thanks,


On Fri, Feb 19, 2016 at 7:10 AM, Jay Hannah <notifications@github.com>
wrote:

> @NW7US <https://github.com/NW7US> hey so currently omaha.pm.org is one of
> my Linodes, which I'll probably shut down soon...
>
> ✗ host omaha.pm.orgomaha.pm.org is an alias for omaha.pm.jays.net.
>
> How do you want to host the website?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perlorg/www.pm.org/pull/79#issuecomment-186206866>.
>



-- 
-= Keep up with current space weather: http://sunspotwatch.com/ =-

Tomas David Hood (Amateur Radio, NW7US)  --  Home page: http://NW7US.us/
<http://nw7us.us/>

Contributing editor, propagation and space weather columns in
  "CQ Amateur Radio Magazine", and in
     "The Spectrum Monitor" ( http://www.thespectrummonitor.com/ )

Twitter:   https://Twitter.com/NW7US <http://twitter.com/NW7US> (@NW7US)
YouTube:   https://YouTube.com/NW7US <https://youtube.com/NW7US>
Tumblr:    http://blog.nw7us.us
Google+    http://nw7us.us/+
Instagram: https://instagram.com/nw7us

Linux User #32405 - Since 1996

The information contained in this communication is confidential,
proprietary, and intended for the addressee(s).  If you are not the
intended recipient, you are hereby notified that any disclosure,
dissemination, distribution or copying of the communication, or
unauthorized use is strictly prohibited.  If you are not the intended
recipient, please delete this message and DO NOT ACT UPON, FORWARD, COPY,
OR OTHERWISE DISSEMINATE IT OR ITS CONTENT

**Comment by jhannah** [comment]
@NW7US we can CNAME DNS to you if your server would respond to omaha.pm.org requests. If not I can set up an Apache redirect. Let me know.

**Comment by NW7US** [comment]
On Tue, Feb 23, 2016 at 6:02 PM, Jay Hannah <notifications@github.com>
wrote:

> omaha.pm.org


I have my apache server accepting for this.  I believe all you have to do
is the DNS assignment, which is:  108.61.16.171




-- 
-= Keep up with current space weather: http://sunspotwatch.com/ =-

Tomas David Hood (Amateur Radio, NW7US)  --  Home page: http://NW7US.us/
<http://nw7us.us/>

Contributing editor, propagation and space weather columns in
  "CQ Amateur Radio Magazine", and in
     "The Spectrum Monitor" ( http://www.thespectrummonitor.com/ )

Twitter:   https://Twitter.com/NW7US <http://twitter.com/NW7US> (@NW7US)
YouTube:   https://YouTube.com/NW7US <https://youtube.com/NW7US>
Tumblr:    http://blog.nw7us.us
Google+    http://nw7us.us/+
Instagram: https://instagram.com/nw7us

Linux User #32405 - Since 1996

The information contained in this communication is confidential,
proprietary, and intended for the addressee(s).  If you are not the
intended recipient, you are hereby notified that any disclosure,
dissemination, distribution or copying of the communication, or
unauthorized use is strictly prohibited.  If you are not the intended
recipient, please delete this message and DO NOT ACT UPON, FORWARD, COPY,
OR OTHERWISE DISSEMINATE IT OR ITS CONTENT

**Comment by jhannah** [comment]
DNS request submitted. Should take in a day or so.

**Comment by NW7US** [comment]
Jay:

It appears that the DNS change is not taking place... can you check on
this, please?  Or, point me to where I must do it.

Thanks.

On Wed, Feb 24, 2016 at 6:08 PM, Jay Hannah <notifications@github.com>
wrote:

> DNS request submitted. Should take in a day or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perlorg/www.pm.org/pull/79#issuecomment-188528426>.
>



-- 
-= Keep up with current space weather: http://sunspotwatch.com/ =-

Tomas David Hood (Amateur Radio, NW7US)  --  Home page: http://NW7US.us/
<http://nw7us.us/>

Contributing editor, propagation and space weather columns in
  "CQ Amateur Radio Magazine", and in
     "The Spectrum Monitor" ( http://www.thespectrummonitor.com/ )

Twitter:   https://Twitter.com/NW7US <http://twitter.com/NW7US> (@NW7US)
YouTube:   https://YouTube.com/NW7US <https://youtube.com/NW7US>
Tumblr:    http://blog.nw7us.us
Google+    http://nw7us.us/+
Instagram: https://instagram.com/nw7us

Linux User #32405 - Since 1996

The information contained in this communication is confidential,
proprietary, and intended for the addressee(s).  If you are not the
intended recipient, you are hereby notified that any disclosure,
dissemination, distribution or copying of the communication, or
unauthorized use is strictly prohibited.  If you are not the intended
recipient, please delete this message and DO NOT ACT UPON, FORWARD, COPY,
OR OTHERWISE DISSEMINATE IT OR ITS CONTENT

**Comment by jhannah** [comment]
Oh, oops. @rspier asked me a question on Feb 25th, I didn't see it. My fault. Hopefully in a day or so.

**Comment by jhannah** [comment]
Looks like it's fixed now :)

**Comment by NW7US** [comment]
Thanks,

The change must not have propagated to my ISP (Cox Cable, Omaha).
http://omaha.pm.org/ still goes to the previous version.  Probably will
bubble down to my connection by tomorrow.



On Wed, Mar 2, 2016 at 5:49 PM, Jay Hannah <notifications@github.com> wrote:

> Looks like it's fixed now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perlorg/www.pm.org/pull/79#issuecomment-191498325>.
>



-- 
-= Keep up with current space weather: http://sunspotwatch.com/ =-

Tomas David Hood (Amateur Radio, NW7US)  --  Home page: http://NW7US.us/
<http://nw7us.us/>

Contributing editor, propagation and space weather columns in
  "CQ Amateur Radio Magazine", and in
     "The Spectrum Monitor" ( http://www.thespectrummonitor.com/ )

Twitter:   https://Twitter.com/NW7US <http://twitter.com/NW7US> (@NW7US)
YouTube:   https://YouTube.com/NW7US <https://youtube.com/NW7US>
Tumblr:    http://blog.nw7us.us
Google+    http://nw7us.us/+
Instagram: https://instagram.com/nw7us

Linux User #32405 - Since 1996

The information contained in this communication is confidential,
proprietary, and intended for the addressee(s).  If you are not the
intended recipient, you are hereby notified that any disclosure,
dissemination, distribution or copying of the communication, or
unauthorized use is strictly prohibited.  If you are not the intended
recipient, please delete this message and DO NOT ACT UPON, FORWARD, COPY,
OR OTHERWISE DISSEMINATE IT OR ITS CONTENT

**Comment by jhannah** [comment]
Ya, should be "just you" at this point.  :)
```
✗ dig +trace @A.ROOT-SERVERS.NET. omaha.pm.org.

; <<>> DiG 9.8.3-P1 <<>> +trace @A.ROOT-SERVERS.NET. omaha.pm.org.
; (1 server found)
;; global options: +cmd
.			518400	IN	NS	i.root-servers.net.
.			518400	IN	NS	m.root-servers.net.
.			518400	IN	NS	c.root-servers.net.
.			518400	IN	NS	g.root-servers.net.
.			518400	IN	NS	e.root-servers.net.
.			518400	IN	NS	l.root-servers.net.
.			518400	IN	NS	d.root-servers.net.
.			518400	IN	NS	b.root-servers.net.
.			518400	IN	NS	j.root-servers.net.
.			518400	IN	NS	h.root-servers.net.
.			518400	IN	NS	k.root-servers.net.
.			518400	IN	NS	f.root-servers.net.
.			518400	IN	NS	a.root-servers.net.
;; Received 496 bytes from 198.41.0.4#53(198.41.0.4) in 424 ms

org.			172800	IN	NS	a0.org.afilias-nst.info.
org.			172800	IN	NS	a2.org.afilias-nst.info.
org.			172800	IN	NS	b0.org.afilias-nst.org.
org.			172800	IN	NS	b2.org.afilias-nst.org.
org.			172800	IN	NS	c0.org.afilias-nst.info.
org.			172800	IN	NS	d0.org.afilias-nst.org.
;; Received 432 bytes from 198.97.190.53#53(198.97.190.53) in 314 ms

pm.org.			86400	IN	NS	ns1.eu.bitnames.com.
pm.org.			86400	IN	NS	ns2.eu.bitnames.com.
pm.org.			86400	IN	NS	ns3.us.bitnames.com.
pm.org.			86400	IN	NS	ns-g1.bitnames.com.
pm.org.			86400	IN	NS	ns1.us.bitnames.com.
pm.org.			86400	IN	NS	ns-g2.bitnames.com.
pm.org.			86400	IN	NS	ns2.us.bitnames.com.
;; Received 178 bytes from 199.19.54.1#53(199.19.54.1) in 328 ms

omaha.pm.org.		7200	IN	A	108.61.16.171
pm.org.			172800	IN	NS	ns1.eu.bitnames.com.
pm.org.			172800	IN	NS	ns1.us.bitnames.com.
pm.org.			172800	IN	NS	ns2.eu.bitnames.com.
pm.org.			172800	IN	NS	ns2.us.bitnames.com.
pm.org.			172800	IN	NS	ns3.us.bitnames.com.
pm.org.			172800	IN	NS	ns-g1.bitnames.com.
pm.org.			172800	IN	NS	ns-g2.bitnames.com.
;; Received 194 bytes from 92.243.1.21#53(92.243.1.21) in 138 ms
```

**Pull request merged**
