### PR TITLE
Added Gotanda.pm

### PR DESCRIPTION
**Pull request by karupanerura**
(1) Where are you going to host your site's website?

http://gotanda.pm.org/ ( http://gotanda-pm.github.io/ )

(2) Do you want us to host a Mailman mailing list for you?

No thanks.

### CODE REVIEW

**Comment by jhannah** [comment]
@rspier hey is dns.txt a live file? Can we just patch it? Or do I still send you emails to request DNS changes? Thanks!

**Comment by jhannah** [comment]
Welcome!
* DNS request submitted (the old fashioned way). Should take in a day or so.
* Added you to the group leader mailing list.
* Flushed website.

**Comment by rspier** [comment]
@jhannah dns.txt is leftover from a previous attempt at automation.  it's over a year old and out of date.  i've deleted it.

**Comment by karupanerura** [comment]
Thank you for accepting!

**Pull request merged**
