### PR TITLE
Add Fuzhou Fujian China PM.ORG

### PR DESCRIPTION
**Pull request by zcns**
Add FuZhou Fujian China ORG

### CODE REVIEW

**Comment by zcns** [comment]
If you agree with the PR, point fuzhou.pm.org to fzsig.github.io.

**Comment by jhannah** [comment]
Sorry, just saw this. Are you no longer wanting this updated?

**Comment by zcns** [comment]
I hope to continue.

**Comment by jhannah** [comment]
@zcns where should we point fuzhou.pm.org DNS?

**Comment by zcns** [comment]
cnorgs.github.io

**Comment by zcns** [comment]
@jhannah

**Comment by jhannah** [comment]
@zcns we need a valid email address so people can reach you via email if they want.
I submitted a DNS request, which should take effect in a couple business days.

**Pull request merged**
