### PR TITLE
Add Fleet.pm

### PR DESCRIPTION
**Pull request by JRaspass**
(1) Where are you going to host your site's website?

http://fleet.pm.org ( http://fleet-pm.github.io )

(2) Do you want us to host a Mailman mailing list for you?

Yes please.

### CODE REVIEW

**Comment by jhannah** [comment]
I submitted a DNS request for you. It should take in a day or so. Thanks! :)

**Comment by JRaspass** [comment]
I think the DNS has been submitted incorrectly, possibly just missing a dot on the end of the CNAME, it's coming up as fleet-pm.github.io.pm.org. which is obviously wrong :-P

**Comment by jhannah** [comment]
ack! @rspier? halp! :)

**Comment by rspier** [comment]
Whoops.  Typo.  Fixed.

**Comment by JRaspass** [comment]
Thanks, everything seems to be working now :+1:

**Pull request merged**
